            package com.github.danielchemko.winmdj.core.autoobject.stubs
            
            
            import com.github.danielchemko.winmdj.core.MdObjectMapper
            import com.github.danielchemko.winmdj.core.autoobject.BaseWinMdStub
            import com.github.danielchemko.winmdj.core.autoobject.model.CLRMetadataType
            import com.github.danielchemko.winmdj.core.mdspec.*
            import com.github.danielchemko.winmdj.parser.WinMdNavigator
            import javax.annotation.processing.Generated
            
            /**
             * THIS FILE IS AUTOMATICALLY GENERATED BY RegenerateSubs.kt. DO NOT EDIT IT BY HAND
             */
            
            @Generated
            class StubMemberReferenceImpl (
                objectMapper: MdObjectMapper,
                navigator: WinMdNavigator,
                index: Int
            ) : MemberReference {

                val stub = BaseWinMdStub(objectMapper, navigator, index)
                
                override fun getStub(): WinMdStub {
                    return stub                   
                }

                override fun getToken(): UInt {
                   return stub.getToken(CLRMetadataType.MEMBER_REF)
                }
                
                override fun getOffset(): UInt {
                   return stub.getObjectTableOffset(CLRMetadataType.MEMBER_REF, 0).toUInt()
                }
                
                override fun copy(rowNum: Int): StubMemberReferenceImpl {
                   return StubMemberReferenceImpl::class.constructors.first().call(stub.getObjectMapper(), stub.getNavigator(), rowNum)
                }
       
            override fun getName(): kotlin.String {
    return stub.lookupString(CLRMetadataType.MEMBER_REF, 1)
}

override fun getParent(): com.github.danielchemko.winmdj.core.mdspec.MemberRefParent? {
    return stub.lookupInterfaceReferent(CLRMetadataType.MEMBER_REF, 0, com.github.danielchemko.winmdj.core.mdspec.MemberRefParent::class)
}

override fun getSignature(): kotlin.ByteArray {
    return stub.lookupBlob(CLRMetadataType.MEMBER_REF, 2)
}
            }