            package com.github.danielchemko.winmdj.core.autoobject.stubs
            
            
            import com.github.danielchemko.winmdj.core.MdObjectMapper
            import com.github.danielchemko.winmdj.core.autoobject.BaseWinMdStub
            import com.github.danielchemko.winmdj.core.autoobject.model.CLRMetadataType
            import com.github.danielchemko.winmdj.core.mdspec.*
            import com.github.danielchemko.winmdj.parser.WinMdNavigator
            import javax.annotation.processing.Generated
            
            /**
             * THIS FILE IS AUTOMATICALLY GENERATED BY RegenerateSubs.kt. DO NOT EDIT IT BY HAND
             */
            
            @Generated
            class StubEventImpl (
                objectMapper: MdObjectMapper,
                navigator: WinMdNavigator,
                index: Int
            ) : Event {

                val stub = BaseWinMdStub(objectMapper, navigator, index)
                
                override fun getStub(): WinMdStub {
                    return stub                   
                }

                override fun getToken(): UInt {
                   return stub.getToken(CLRMetadataType.EVENT)
                }
                
                override fun getOffset(): UInt {
                   return stub.getObjectTableOffset(CLRMetadataType.EVENT, 0).toUInt()
                }
                
                override fun copy(rowNum: Int): StubEventImpl {
                   return StubEventImpl::class.constructors.first().call(stub.getObjectMapper(), stub.getNavigator(), rowNum)
                }
       
            override fun getAttributes(): java.util.BitSet {
    return stub.lookupBitset(CLRMetadataType.EVENT, 0)
}

override fun getName(): kotlin.String {
    return stub.lookupTableValue(CLRMetadataType.EVENT, 1, kotlin.String::class)!!
}

                            override fun getParent(): com.github.danielchemko.winmdj.core.mdspec.EventMap {
                                val stubsCursor = getStub().getObjectMapper().getCursor(com.github.danielchemko.winmdj.core.mdspec.Event::class.java)
var rowRef = getStub().getRowNumber() - 1;
var highestMethod: com.github.danielchemko.winmdj.core.mdspec.Event = this
return getStub().getReverseReferentSingle(CLRMetadataType.EVENT_MAP, -1, com.github.danielchemko.winmdj.core.mdspec.EventMap::class, highestMethod.getToken())!!
                            }

override fun getTypeDefOrRef(): com.github.danielchemko.winmdj.core.mdspec.TypeDefOrRef? {
    return stub.lookupInterfaceReferent(CLRMetadataType.EVENT, 2, com.github.danielchemko.winmdj.core.mdspec.TypeDefOrRef::class)
}

                            override fun getSemantics(): com.github.danielchemko.winmdj.core.mdspec.MethodSemantics {
                                val stubsCursor = getStub().getObjectMapper().getCursor(com.github.danielchemko.winmdj.core.mdspec.Event::class.java)
var rowRef = getStub().getRowNumber() - 1;
var highestMethod: com.github.danielchemko.winmdj.core.mdspec.Event = this
return getStub().getReverseReferentSingle(CLRMetadataType.METHOD_SEMANTICS, -1, com.github.danielchemko.winmdj.core.mdspec.MethodSemantics::class, highestMethod.getToken())!!
                            }
            }