            package com.github.danielchemko.winmdj.core.autoobject.stubs
            
            
            import com.github.danielchemko.winmdj.core.MdObjectMapper
            import com.github.danielchemko.winmdj.core.autoobject.WinMdStub
            import com.github.danielchemko.winmdj.core.mdspec.CLRMetadataType
            import com.github.danielchemko.winmdj.core.mdspec.*
            import com.github.danielchemko.winmdj.parser.WinMdNavigator
            import javax.annotation.processing.Generated
            
            /**
             * THIS FILE IS AUTOMATICALLY GENERATED BY RegenerateSubs.kt. DO NOT EDIT IT BY HAND
             */
            
            @Generated
            class StubFieldImpl (
                objectMapper: MdObjectMapper,
                navigator: WinMdNavigator,
                index: Int
            ) : Field {

                private val stub = WinMdStub(objectMapper, navigator, index)
                
                override fun toString(): String {
                   return "Field/${getToken()}"
                }
                
                override fun getStub(): WinMdStub {
                    return stub                   
                }
                
                override fun getRowNumber(): Int {
                    return getStub().getRowNumber()
                }

                override fun getToken(): UInt {
                   return stub.getToken(CLRMetadataType.FIELD)
                }
                
                override fun getOffset(): UInt {
                   return stub.getObjectTableOffset(CLRMetadataType.FIELD, 0).toUInt()
                }
                
                override fun copy(rowNum: Int?): StubFieldImpl {
                   return StubFieldImpl::class.constructors.first().call(stub.getObjectMapper(), stub.getNavigator(), rowNum ?: getRowNumber())
                }
       
            override fun getAttributes(): java.util.BitSet {
    return stub.lookupBitset(CLRMetadataType.FIELD, 0)
}

override fun getName(): kotlin.String {
    return stub.lookupString(CLRMetadataType.FIELD, 1)
}

                            override fun getParent(): com.github.danielchemko.winmdj.core.mdspec.TypeDefinition? {
                                return getStub().computeReverseLookup(
    Field::class,
    4,
    com.github.danielchemko.winmdj.core.mdspec.TypeDefinition::class,
    false,
) as com.github.danielchemko.winmdj.core.mdspec.TypeDefinition?
                            }

override fun getSignature(): kotlin.ByteArray {
    return stub.lookupBlob(CLRMetadataType.FIELD, 2)
}

                            override fun getConstant(): com.github.danielchemko.winmdj.core.mdspec.Constant? {
                                return getStub().computeReverseLookup(
    Field::class,
    1,
    com.github.danielchemko.winmdj.core.mdspec.Constant::class,
    false,
) as com.github.danielchemko.winmdj.core.mdspec.Constant?
                            }

                            override fun getCustomAttribute(): com.github.danielchemko.winmdj.core.mdspec.CustomAttribute? {
                                return getStub().computeReverseLookup(
    Field::class,
    0,
    com.github.danielchemko.winmdj.core.mdspec.CustomAttribute::class,
    false,
) as com.github.danielchemko.winmdj.core.mdspec.CustomAttribute?
                            }

                            override fun getFieldMarshal(): com.github.danielchemko.winmdj.core.mdspec.FieldMarshal? {
                                return getStub().computeReverseLookup(
    Field::class,
    0,
    com.github.danielchemko.winmdj.core.mdspec.FieldMarshal::class,
    false,
) as com.github.danielchemko.winmdj.core.mdspec.FieldMarshal?
                            }

                            override fun getImplementationMap(): com.github.danielchemko.winmdj.core.mdspec.ImplementationMap? {
                                return getStub().computeReverseLookup(
    Field::class,
    1,
    com.github.danielchemko.winmdj.core.mdspec.ImplementationMap::class,
    false,
) as com.github.danielchemko.winmdj.core.mdspec.ImplementationMap?
                            }
            }