            package com.github.danielchemko.winmdj.core.autoobject.stubs
            
            
            import com.github.danielchemko.winmdj.core.MdObjectMapper
            import com.github.danielchemko.winmdj.core.autoobject.WinMdStub
            import com.github.danielchemko.winmdj.core.mdspec.CLRMetadataType
            import com.github.danielchemko.winmdj.core.mdspec.*
            import com.github.danielchemko.winmdj.parser.WinMdNavigator
            import javax.annotation.processing.Generated
            
            /**
             * THIS FILE IS AUTOMATICALLY GENERATED BY RegenerateSubs.kt. DO NOT EDIT IT BY HAND
             */
            
            @Generated
            class StubMethodImplementationImpl (
                objectMapper: MdObjectMapper,
                navigator: WinMdNavigator,
                index: Int
            ) : MethodImplementation {

                private val stub = WinMdStub(objectMapper, navigator, index)
                
                override fun toString(): String {
                   return "MethodImplementation/${getToken()}"
                }
                
                override fun getStub(): WinMdStub {
                    return stub                   
                }
                
                override fun getRowNumber(): Int {
                    return getStub().getRowNumber()
                }

                override fun getToken(): UInt {
                   return stub.getToken(CLRMetadataType.METHOD_IMPL)
                }
                
                override fun getOffset(): UInt {
                   return stub.getObjectTableOffset(CLRMetadataType.METHOD_IMPL, 0).toUInt()
                }
                
                override fun copy(rowNum: Int?): StubMethodImplementationImpl {
                   return StubMethodImplementationImpl::class.constructors.first().call(stub.getObjectMapper(), stub.getNavigator(), rowNum ?: getRowNumber())
                }
       
            override fun getMethodBody(): com.github.danielchemko.winmdj.core.mdspec.MethodDefOrRef? {
    return stub.lookupInterfaceReferent(CLRMetadataType.METHOD_IMPL, 2, com.github.danielchemko.winmdj.core.mdspec.MethodDefOrRef::class)
}

override fun getMethodDeclaration(): com.github.danielchemko.winmdj.core.mdspec.MethodDefOrRef? {
    return stub.lookupInterfaceReferent(CLRMetadataType.METHOD_IMPL, 1, com.github.danielchemko.winmdj.core.mdspec.MethodDefOrRef::class)
}

override fun getType(): com.github.danielchemko.winmdj.core.mdspec.TypeDefinition? {
    return stub.lookupConcreteReferent(CLRMetadataType.METHOD_IMPL, 0, com.github.danielchemko.winmdj.core.mdspec.TypeDefinition::class)
}
            }