package com.github.danielchemko.winmdj.core.autoobject.stubs


import com.github.danielchemko.winmdj.core.MdObjectMapper
import com.github.danielchemko.winmdj.core.autoobject.BaseWinMdStub
import com.github.danielchemko.winmdj.core.autoobject.model.CLRMetadataType
import com.github.danielchemko.winmdj.core.mdspec.AssemblyReferenceProcessor
import com.github.danielchemko.winmdj.core.mdspec.WinMdStub
import com.github.danielchemko.winmdj.parser.WinMdNavigator
import javax.annotation.processing.Generated

/**
 * THIS FILE IS AUTOMATICALLY GENERATED BY RegenerateSubs.kt. DO NOT EDIT IT BY HAND
 */

@Generated
class StubAssemblyReferenceProcessorImpl(
    objectMapper: MdObjectMapper,
    navigator: WinMdNavigator,
    index: Int
) : AssemblyReferenceProcessor {

    val stub = BaseWinMdStub(objectMapper, navigator, index)

    override fun getStub(): WinMdStub {
        return stub
    }

    override fun getToken(): UInt {
        return stub.getToken(CLRMetadataType.ASSEMBLY_REF_PROCESSOR)
    }

    override fun getOffset(): UInt {
        return stub.getObjectTableOffset(CLRMetadataType.ASSEMBLY_REF_PROCESSOR, 0).toUInt()
    }

    override fun copy(rowNum: Int): StubAssemblyReferenceProcessorImpl {
        return StubAssemblyReferenceProcessorImpl::class.constructors.first()
            .call(stub.getObjectMapper(), stub.getNavigator(), rowNum)
    }

    override fun getAssemblyRef(): com.github.danielchemko.winmdj.core.mdspec.AssemblyReference? {
        return stub.lookupConcreteReferent(
            CLRMetadataType.ASSEMBLY_REF_PROCESSOR,
            1,
            com.github.danielchemko.winmdj.core.mdspec.AssemblyReference::class
        )
    }

    override fun getProcessor(): kotlin.UInt {
        return stub.lookupTableValue(CLRMetadataType.ASSEMBLY_REF_PROCESSOR, 0, kotlin.UInt::class)!!
    }
}