            package com.github.danielchemko.winmdj.core.autoobject.stubs
            
            
            import com.github.danielchemko.winmdj.core.MdObjectMapper
            import com.github.danielchemko.winmdj.core.autoobject.BaseWinMdStub
            import com.github.danielchemko.winmdj.core.autoobject.model.CLRMetadataType
            import com.github.danielchemko.winmdj.core.mdspec.*
            import com.github.danielchemko.winmdj.parser.WinMdNavigator
            import javax.annotation.processing.Generated
            
            /**
             * THIS FILE IS AUTOMATICALLY GENERATED BY RegenerateSubs.kt. DO NOT EDIT IT BY HAND
             */
            
            @Generated
            class StubSecurityAttributeImpl (
                objectMapper: MdObjectMapper,
                navigator: WinMdNavigator,
                index: Int
            ) : SecurityAttribute {

                val stub = BaseWinMdStub(objectMapper, navigator, index)
                
                override fun getStub(): WinMdStub {
                    return stub                   
                }

                override fun getToken(): UInt {
                   return stub.getToken(CLRMetadataType.DECL_SECURITY)
                }
                
                override fun getOffset(): UInt {
                   return stub.getObjectTableOffset(CLRMetadataType.DECL_SECURITY, 0).toUInt()
                }
                
                override fun copy(rowNum: Int): StubSecurityAttributeImpl {
                   return StubSecurityAttributeImpl::class.constructors.first().call(stub.getObjectMapper(), stub.getNavigator(), rowNum)
                }
       
            override fun getAction(): kotlin.UShort {
    return stub.lookupTableValue(CLRMetadataType.DECL_SECURITY, 0, kotlin.UShort::class)!!
}

override fun getParent(): com.github.danielchemko.winmdj.core.mdspec.HasDeclSecurity? {
    return stub.lookupInterfaceReferent(CLRMetadataType.DECL_SECURITY, 1, com.github.danielchemko.winmdj.core.mdspec.HasDeclSecurity::class)
}

override fun getPermissionSet(): kotlin.ByteArray {
    return stub.lookupBlob(CLRMetadataType.DECL_SECURITY, 2)
}
            }