            package com.github.danielchemko.winmdj.core.autoobject.stubs
            
            
            import com.github.danielchemko.winmdj.core.MdObjectMapper
            import com.github.danielchemko.winmdj.core.autoobject.WinMdStub
            import com.github.danielchemko.winmdj.core.mdspec.CLRMetadataType
            import com.github.danielchemko.winmdj.core.mdspec.*
            import com.github.danielchemko.winmdj.parser.WinMdNavigator
            import javax.annotation.processing.Generated
            
            /**
             * THIS FILE IS AUTOMATICALLY GENERATED BY RegenerateSubs.kt. DO NOT EDIT IT BY HAND
             */
            
            @Generated
            class StubAssemblyReferenceProcessorImpl (
                objectMapper: MdObjectMapper,
                navigator: WinMdNavigator,
                index: Int
            ) : AssemblyReferenceProcessor {

                private val stub = WinMdStub(objectMapper, navigator, index)
                
                override fun toString(): String {
                   return "AssemblyReferenceProcessor/${getToken()}"
                }
                
                override fun getStub(): WinMdStub {
                    return stub                   
                }
                
                override fun getRowNumber(): Int {
                    return getStub().getRowNumber()
                }

                override fun getToken(): UInt {
                   return stub.getToken(CLRMetadataType.ASSEMBLY_REF_PROCESSOR)
                }
                
                override fun getOffset(): UInt {
                   return stub.getObjectTableOffset(CLRMetadataType.ASSEMBLY_REF_PROCESSOR, 0).toUInt()
                }
                
                override fun copy(rowNum: Int?): StubAssemblyReferenceProcessorImpl {
                   return StubAssemblyReferenceProcessorImpl::class.constructors.first().call(stub.getObjectMapper(), stub.getNavigator(), rowNum ?: getRowNumber())
                }
       
            override fun getAssemblyRef(): com.github.danielchemko.winmdj.core.mdspec.AssemblyReference? {
    return stub.lookupConcreteReferent(CLRMetadataType.ASSEMBLY_REF_PROCESSOR, 1, com.github.danielchemko.winmdj.core.mdspec.AssemblyReference::class)
}

override fun getProcessor(): kotlin.UInt {
    return stub.lookupTableValue(CLRMetadataType.ASSEMBLY_REF_PROCESSOR, 0, kotlin.UInt::class)!!
}
            }