            package com.github.danielchemko.winmdj.core.autoobject.stubs
            
            
            import com.github.danielchemko.winmdj.core.MdObjectMapper
            import com.github.danielchemko.winmdj.core.autoobject.WinMdStub
            import com.github.danielchemko.winmdj.core.mdspec.CLRMetadataType
            import com.github.danielchemko.winmdj.core.mdspec.*
            import com.github.danielchemko.winmdj.parser.WinMdNavigator
            import javax.annotation.processing.Generated
            
            /**
             * THIS FILE IS AUTOMATICALLY GENERATED BY RegenerateSubs.kt. DO NOT EDIT IT BY HAND
             */
            
            @Generated
            class StubConstantImpl (
                objectMapper: MdObjectMapper,
                navigator: WinMdNavigator,
                index: Int
            ) : Constant {

                private val stub = WinMdStub(objectMapper, navigator, index)
                
                override fun toString(): String {
                   return "Constant/${getToken()}"
                }
                
                override fun getStub(): WinMdStub {
                    return stub                   
                }
                
                override fun getRowNumber(): Int {
                    return getStub().getRowNumber()
                }

                override fun getToken(): UInt {
                   return stub.getToken(CLRMetadataType.CONSTANT)
                }
                
                override fun getOffset(): UInt {
                   return stub.getObjectTableOffset(CLRMetadataType.CONSTANT, 0).toUInt()
                }
                
                override fun copy(rowNum: Int?): StubConstantImpl {
                   return StubConstantImpl::class.constructors.first().call(stub.getObjectMapper(), stub.getNavigator(), rowNum ?: getRowNumber())
                }
       
            override fun getParent(): com.github.danielchemko.winmdj.core.mdspec.HasConstant? {
    return stub.lookupInterfaceReferent(CLRMetadataType.CONSTANT, 1, com.github.danielchemko.winmdj.core.mdspec.HasConstant::class)
}

override fun getRawType(): kotlin.UShort {
    return stub.lookupTableValue(CLRMetadataType.CONSTANT, 0, kotlin.UShort::class)!!
}

override fun getValueBlob(): kotlin.ByteArray {
    return stub.lookupBlob(CLRMetadataType.CONSTANT, 2)
}
            }