package com.github.danielchemko.winmdj.core.autoobject.stubs


import com.github.danielchemko.winmdj.core.MdObjectMapper
import com.github.danielchemko.winmdj.core.autoobject.BaseWinMdStub
import com.github.danielchemko.winmdj.core.autoobject.model.CLRMetadataType
import com.github.danielchemko.winmdj.core.mdspec.GenericParameterConstraint
import com.github.danielchemko.winmdj.core.mdspec.WinMdStub
import com.github.danielchemko.winmdj.parser.WinMdNavigator
import javax.annotation.processing.Generated

/**
 * THIS FILE IS AUTOMATICALLY GENERATED BY RegenerateSubs.kt. DO NOT EDIT IT BY HAND
 */

@Generated
class StubGenericParameterConstraintImpl(
    objectMapper: MdObjectMapper,
    navigator: WinMdNavigator,
    index: Int
) : GenericParameterConstraint {

    val stub = BaseWinMdStub(objectMapper, navigator, index)

    override fun getStub(): WinMdStub {
        return stub
    }

    override fun getToken(): UInt {
        return stub.getToken(CLRMetadataType.GENERIC_PARAM_CONSTRAINT)
    }

    override fun getOffset(): UInt {
        return stub.getObjectTableOffset(CLRMetadataType.GENERIC_PARAM_CONSTRAINT, 0).toUInt()
    }

    override fun copy(rowNum: Int): StubGenericParameterConstraintImpl {
        return StubGenericParameterConstraintImpl::class.constructors.first()
            .call(stub.getObjectMapper(), stub.getNavigator(), rowNum)
    }

    override fun getOwner(): com.github.danielchemko.winmdj.core.mdspec.GenericParameter {
        return stub.lookupConcreteReferent(
            CLRMetadataType.GENERIC_PARAM_CONSTRAINT,
            0,
            com.github.danielchemko.winmdj.core.mdspec.GenericParameter::class
        )!!
    }

    override fun getType(): com.github.danielchemko.winmdj.core.mdspec.TypeDefinition {
        return stub.lookupConcreteReferent(
            CLRMetadataType.GENERIC_PARAM_CONSTRAINT,
            1,
            com.github.danielchemko.winmdj.core.mdspec.TypeDefinition::class
        )!!
    }

    override fun getCustomAttribute(): com.github.danielchemko.winmdj.core.mdspec.CustomAttribute? {
        return getStub().computeReverseLookup(
            CLRMetadataType.GENERIC_PARAM_CONSTRAINT,
            GenericParameterConstraint::class,
            0,
            -1,
            0,
            com.github.danielchemko.winmdj.core.mdspec.CustomAttribute::class,
            false,
        ) as com.github.danielchemko.winmdj.core.mdspec.CustomAttribute?
    }
}