            package com.github.danielchemko.winmdj.core.autoobject.stubs
            
            
            import com.github.danielchemko.winmdj.core.MdObjectMapper
            import com.github.danielchemko.winmdj.core.autoobject.WinMdStub
            import com.github.danielchemko.winmdj.core.mdspec.CLRMetadataType
            import com.github.danielchemko.winmdj.core.mdspec.*
            import com.github.danielchemko.winmdj.parser.WinMdNavigator
            import javax.annotation.processing.Generated
            
            /**
             * THIS FILE IS AUTOMATICALLY GENERATED BY RegenerateSubs.kt. DO NOT EDIT IT BY HAND
             */
            
            @Generated
            class StubMethodSemanticsImpl (
                objectMapper: MdObjectMapper,
                navigator: WinMdNavigator,
                index: Int
            ) : MethodSemantics {

                private val stub = WinMdStub(objectMapper, navigator, index)
                
                override fun toString(): String {
                   return "MethodSemantics/${getToken()}"
                }
                
                override fun getStub(): WinMdStub {
                    return stub                   
                }
                
                override fun getRowNumber(): Int {
                    return getStub().getRowNumber()
                }

                override fun getToken(): UInt {
                   return stub.getToken(CLRMetadataType.METHOD_SEMANTICS)
                }
                
                override fun getOffset(): UInt {
                   return stub.getObjectTableOffset(CLRMetadataType.METHOD_SEMANTICS, 0).toUInt()
                }
                
                override fun copy(rowNum: Int?): StubMethodSemanticsImpl {
                   return StubMethodSemanticsImpl::class.constructors.first().call(stub.getObjectMapper(), stub.getNavigator(), rowNum ?: getRowNumber())
                }
       
            override fun getAssociation(): com.github.danielchemko.winmdj.core.mdspec.HasSemantics? {
    return stub.lookupInterfaceReferent(CLRMetadataType.METHOD_SEMANTICS, 2, com.github.danielchemko.winmdj.core.mdspec.HasSemantics::class)
}

override fun getAttribute(): java.util.BitSet {
    return stub.lookupBitset(CLRMetadataType.METHOD_SEMANTICS, 0)
}

override fun getMethod(): com.github.danielchemko.winmdj.core.mdspec.MethodDefinition? {
    return stub.lookupConcreteReferent(CLRMetadataType.METHOD_SEMANTICS, 1, com.github.danielchemko.winmdj.core.mdspec.MethodDefinition::class)
}
            }