package com.github.danielchemko.winmdj.core.autoobject.stubs


import com.github.danielchemko.winmdj.core.MdObjectMapper
import com.github.danielchemko.winmdj.core.autoobject.BaseWinMdStub
import com.github.danielchemko.winmdj.core.autoobject.model.CLRMetadataType
import com.github.danielchemko.winmdj.core.mdspec.TypeReference
import com.github.danielchemko.winmdj.core.mdspec.WinMdStub
import com.github.danielchemko.winmdj.parser.WinMdNavigator
import javax.annotation.processing.Generated

/**
 * THIS FILE IS AUTOMATICALLY GENERATED BY RegenerateSubs.kt. DO NOT EDIT IT BY HAND
 */

@Generated
class StubTypeReferenceImpl(
    objectMapper: MdObjectMapper,
    navigator: WinMdNavigator,
    index: Int
) : TypeReference {

    val stub = BaseWinMdStub(objectMapper, navigator, index)

    override fun getStub(): WinMdStub {
        return stub
    }

    override fun getToken(): UInt {
        return stub.getToken(CLRMetadataType.TYPE_REF)
    }

    override fun getOffset(): UInt {
        return stub.getObjectTableOffset(CLRMetadataType.TYPE_REF, 0).toUInt()
    }

    override fun copy(rowNum: Int): StubTypeReferenceImpl {
        return StubTypeReferenceImpl::class.constructors.first()
            .call(stub.getObjectMapper(), stub.getNavigator(), rowNum)
    }

    override fun getName(): kotlin.String {
        return stub.lookupString(CLRMetadataType.TYPE_REF, 1)
    }

    override fun getNamespace(): kotlin.String {
        return stub.lookupString(CLRMetadataType.TYPE_REF, 2)
    }

    override fun getResolutionScope(): com.github.danielchemko.winmdj.core.mdspec.ResolutionScope? {
        return stub.lookupInterfaceReferent(
            CLRMetadataType.TYPE_REF,
            0,
            com.github.danielchemko.winmdj.core.mdspec.ResolutionScope::class
        )
    }

    override fun getChildTypeReferences(): kotlin.collections.List<com.github.danielchemko.winmdj.core.mdspec.TypeReference> {
        return getStub().computeReverseLookup(
            CLRMetadataType.TYPE_REF,
            TypeReference::class,
            0,
            -1,
            0,
            com.github.danielchemko.winmdj.core.mdspec.TypeReference::class,
            true,
        )!! as kotlin.collections.List<com.github.danielchemko.winmdj.core.mdspec.TypeReference>
    }

    override fun getCustomAttribute(): com.github.danielchemko.winmdj.core.mdspec.CustomAttribute? {
        return getStub().computeReverseLookup(
            CLRMetadataType.TYPE_REF,
            TypeReference::class,
            0,
            -1,
            0,
            com.github.danielchemko.winmdj.core.mdspec.CustomAttribute::class,
            false,
        ) as com.github.danielchemko.winmdj.core.mdspec.CustomAttribute?
    }

    override fun getEvents(): kotlin.collections.List<com.github.danielchemko.winmdj.core.mdspec.Event> {
        return getStub().computeReverseLookup(
            CLRMetadataType.TYPE_REF,
            TypeReference::class,
            2,
            -1,
            0,
            com.github.danielchemko.winmdj.core.mdspec.Event::class,
            true,
        )!! as kotlin.collections.List<com.github.danielchemko.winmdj.core.mdspec.Event>
    }

    override fun getMemberReference(): com.github.danielchemko.winmdj.core.mdspec.MemberReference? {
        return getStub().computeReverseLookup(
            CLRMetadataType.TYPE_REF,
            TypeReference::class,
            0,
            -1,
            0,
            com.github.danielchemko.winmdj.core.mdspec.MemberReference::class,
            false,
        ) as com.github.danielchemko.winmdj.core.mdspec.MemberReference?
    }

    override fun getSubTypes(): kotlin.collections.List<com.github.danielchemko.winmdj.core.mdspec.TypeDefinition> {
        return getStub().computeReverseLookup(
            CLRMetadataType.TYPE_REF,
            TypeReference::class,
            3,
            -1,
            0,
            com.github.danielchemko.winmdj.core.mdspec.TypeDefinition::class,
            true,
        )!! as kotlin.collections.List<com.github.danielchemko.winmdj.core.mdspec.TypeDefinition>
    }
}