            package com.github.danielchemko.winmdj.core.autoobject.stubs
            
            
            import com.github.danielchemko.winmdj.core.MdObjectMapper
            import com.github.danielchemko.winmdj.core.autoobject.WinMdStub
            import com.github.danielchemko.winmdj.core.mdspec.CLRMetadataType
            import com.github.danielchemko.winmdj.core.mdspec.*
            import com.github.danielchemko.winmdj.parser.WinMdNavigator
            import javax.annotation.processing.Generated
            
            /**
             * THIS FILE IS AUTOMATICALLY GENERATED BY RegenerateSubs.kt. DO NOT EDIT IT BY HAND
             */
            
            @Generated
            class StubParameterImpl (
                objectMapper: MdObjectMapper,
                navigator: WinMdNavigator,
                index: Int
            ) : Parameter {

                private val stub = WinMdStub(objectMapper, navigator, index)
                
                override fun toString(): String {
                   return "Parameter/${getToken()}"
                }
                
                override fun getStub(): WinMdStub {
                    return stub                   
                }
                
                override fun getRowNumber(): Int {
                    return getStub().getRowNumber()
                }

                override fun getToken(): UInt {
                   return stub.getToken(CLRMetadataType.PARAM)
                }
                
                override fun getOffset(): UInt {
                   return stub.getObjectTableOffset(CLRMetadataType.PARAM, 0).toUInt()
                }
                
                override fun copy(rowNum: Int?): StubParameterImpl {
                   return StubParameterImpl::class.constructors.first().call(stub.getObjectMapper(), stub.getNavigator(), rowNum ?: getRowNumber())
                }
       
            override fun getAttributes(): java.util.BitSet {
    return stub.lookupBitset(CLRMetadataType.PARAM, 0)
}

override fun getName(): kotlin.String {
    return stub.lookupString(CLRMetadataType.PARAM, 2)
}

override fun getSequence(): kotlin.UShort {
    return stub.lookupTableValue(CLRMetadataType.PARAM, 1, kotlin.UShort::class)!!
}

                            override fun getConstant(): com.github.danielchemko.winmdj.core.mdspec.Constant? {
                                return getStub().computeReverseLookup(
    Parameter::class,
    1,
    com.github.danielchemko.winmdj.core.mdspec.Constant::class,
    false,
) as com.github.danielchemko.winmdj.core.mdspec.Constant?
                            }

                            override fun getCustomAttribute(): com.github.danielchemko.winmdj.core.mdspec.CustomAttribute? {
                                return getStub().computeReverseLookup(
    Parameter::class,
    0,
    com.github.danielchemko.winmdj.core.mdspec.CustomAttribute::class,
    false,
) as com.github.danielchemko.winmdj.core.mdspec.CustomAttribute?
                            }

                            override fun getFieldMarshal(): com.github.danielchemko.winmdj.core.mdspec.FieldMarshal? {
                                return getStub().computeReverseLookup(
    Parameter::class,
    0,
    com.github.danielchemko.winmdj.core.mdspec.FieldMarshal::class,
    false,
) as com.github.danielchemko.winmdj.core.mdspec.FieldMarshal?
                            }
            }