package com.github.danielchemko.winmdj.core.autoobject.stubs


import com.github.danielchemko.winmdj.core.MdObjectMapper
import com.github.danielchemko.winmdj.core.autoobject.BaseWinMdStub
import com.github.danielchemko.winmdj.core.autoobject.model.CLRMetadataType
import com.github.danielchemko.winmdj.core.mdspec.EventMap
import com.github.danielchemko.winmdj.core.mdspec.WinMdStub
import com.github.danielchemko.winmdj.parser.WinMdNavigator
import javax.annotation.processing.Generated

/**
 * THIS FILE IS AUTOMATICALLY GENERATED BY RegenerateSubs.kt. DO NOT EDIT IT BY HAND
 */

@Generated
class StubEventMapImpl(
    objectMapper: MdObjectMapper,
    navigator: WinMdNavigator,
    index: Int
) : EventMap {

    val stub = BaseWinMdStub(objectMapper, navigator, index)

    override fun getStub(): WinMdStub {
        return stub
    }

    override fun getToken(): UInt {
        return stub.getToken(CLRMetadataType.EVENT_MAP)
    }

    override fun getOffset(): UInt {
        return stub.getObjectTableOffset(CLRMetadataType.EVENT_MAP, 0).toUInt()
    }

    override fun copy(rowNum: Int): StubEventMapImpl {
        return StubEventMapImpl::class.constructors.first().call(stub.getObjectMapper(), stub.getNavigator(), rowNum)
    }

    override fun getEvents(): kotlin.collections.List<com.github.danielchemko.winmdj.core.mdspec.Event> {
        val column =
            return stub.lookupList(
                CLRMetadataType.EVENT_MAP,
                1,
                2,
                2,
                com.github.danielchemko.winmdj.core.mdspec.Event::class
            )
    }

    override fun getParent(): com.github.danielchemko.winmdj.core.mdspec.TypeDefinition? {
        return stub.lookupConcreteReferent(
            CLRMetadataType.EVENT_MAP,
            0,
            com.github.danielchemko.winmdj.core.mdspec.TypeDefinition::class
        )
    }
}