            package com.github.danielchemko.winmdj.core.autoobject.stubs
            
            
            import com.github.danielchemko.winmdj.core.MdObjectMapper
            import com.github.danielchemko.winmdj.core.autoobject.WinMdStub
            import com.github.danielchemko.winmdj.core.mdspec.CLRMetadataType
            import com.github.danielchemko.winmdj.core.mdspec.*
            import com.github.danielchemko.winmdj.parser.WinMdNavigator
            import javax.annotation.processing.Generated
            
            /**
             * THIS FILE IS AUTOMATICALLY GENERATED BY RegenerateSubs.kt. DO NOT EDIT IT BY HAND
             */
            
            @Generated
            class StubGenericParameterImpl (
                objectMapper: MdObjectMapper,
                navigator: WinMdNavigator,
                index: Int
            ) : GenericParameter {

                private val stub = WinMdStub(objectMapper, navigator, index)
                
                override fun toString(): String {
                   return "GenericParameter/${getToken()}"
                }
                
                override fun getStub(): WinMdStub {
                    return stub                   
                }
                
                override fun getRowNumber(): Int {
                    return getStub().getRowNumber()
                }

                override fun getToken(): UInt {
                   return stub.getToken(CLRMetadataType.GENERIC_PARAM)
                }
                
                override fun getOffset(): UInt {
                   return stub.getObjectTableOffset(CLRMetadataType.GENERIC_PARAM, 0).toUInt()
                }
                
                override fun copy(rowNum: Int?): StubGenericParameterImpl {
                   return StubGenericParameterImpl::class.constructors.first().call(stub.getObjectMapper(), stub.getNavigator(), rowNum ?: getRowNumber())
                }
       
            override fun getAttributes(): java.util.BitSet {
    return stub.lookupBitset(CLRMetadataType.GENERIC_PARAM, 1)
}

override fun getName(): kotlin.String {
    return stub.lookupString(CLRMetadataType.GENERIC_PARAM, 3)
}

override fun getNumber(): kotlin.UShort {
    return stub.lookupTableValue(CLRMetadataType.GENERIC_PARAM, 0, kotlin.UShort::class)!!
}

override fun getOwner(): com.github.danielchemko.winmdj.core.mdspec.TypeOrMethodDef? {
    return stub.lookupInterfaceReferent(CLRMetadataType.GENERIC_PARAM, 2, com.github.danielchemko.winmdj.core.mdspec.TypeOrMethodDef::class)
}

                            override fun getCustomAttribute(): com.github.danielchemko.winmdj.core.mdspec.CustomAttribute? {
                                return getStub().computeReverseLookup(
    GenericParameter::class,
    0,
    com.github.danielchemko.winmdj.core.mdspec.CustomAttribute::class,
    false,
) as com.github.danielchemko.winmdj.core.mdspec.CustomAttribute?
                            }
            }