package com.github.danielchemko.winmdj.core.autoobject.stubs


import com.github.danielchemko.winmdj.core.MdObjectMapper
import com.github.danielchemko.winmdj.core.autoobject.BaseWinMdStub
import com.github.danielchemko.winmdj.core.autoobject.model.CLRMetadataType
import com.github.danielchemko.winmdj.core.mdspec.MethodSpecification
import com.github.danielchemko.winmdj.core.mdspec.WinMdStub
import com.github.danielchemko.winmdj.parser.WinMdNavigator
import javax.annotation.processing.Generated

/**
 * THIS FILE IS AUTOMATICALLY GENERATED BY RegenerateSubs.kt. DO NOT EDIT IT BY HAND
 */

@Generated
class StubMethodSpecificationImpl(
    objectMapper: MdObjectMapper,
    navigator: WinMdNavigator,
    index: Int
) : MethodSpecification {

    val stub = BaseWinMdStub(objectMapper, navigator, index)

    override fun getStub(): WinMdStub {
        return stub
    }

    override fun getToken(): UInt {
        return stub.getToken(CLRMetadataType.METHOD_SPEC)
    }

    override fun getOffset(): UInt {
        return stub.getObjectTableOffset(CLRMetadataType.METHOD_SPEC, 0).toUInt()
    }

    override fun copy(rowNum: Int): StubMethodSpecificationImpl {
        return StubMethodSpecificationImpl::class.constructors.first()
            .call(stub.getObjectMapper(), stub.getNavigator(), rowNum)
    }

    override fun getMethod(): com.github.danielchemko.winmdj.core.mdspec.MethodDefOrRef? {
        return stub.lookupInterfaceReferent(
            CLRMetadataType.METHOD_SPEC,
            0,
            com.github.danielchemko.winmdj.core.mdspec.MethodDefOrRef::class
        )
    }

    override fun getSignature(): kotlin.ByteArray {
        return stub.lookupBlob(CLRMetadataType.METHOD_SPEC, 1)
    }

    override fun getCustomAttribute(): com.github.danielchemko.winmdj.core.mdspec.CustomAttribute? {
        return getStub().computeReverseLookup(
            CLRMetadataType.METHOD_SPEC,
            MethodSpecification::class,
            0,
            -1,
            0,
            com.github.danielchemko.winmdj.core.mdspec.CustomAttribute::class,
            false,
        ) as com.github.danielchemko.winmdj.core.mdspec.CustomAttribute?
    }
}