package com.github.danielchemko.winmdj.core.autoobject.stubs


import com.github.danielchemko.winmdj.core.MdObjectMapper
import com.github.danielchemko.winmdj.core.autoobject.BaseWinMdStub
import com.github.danielchemko.winmdj.core.autoobject.model.CLRMetadataType
import com.github.danielchemko.winmdj.core.mdspec.FieldRva
import com.github.danielchemko.winmdj.core.mdspec.WinMdStub
import com.github.danielchemko.winmdj.parser.WinMdNavigator
import javax.annotation.processing.Generated

/**
 * THIS FILE IS AUTOMATICALLY GENERATED BY RegenerateSubs.kt. DO NOT EDIT IT BY HAND
 */

@Generated
class StubFieldRvaImpl(
    objectMapper: MdObjectMapper,
    navigator: WinMdNavigator,
    index: Int
) : FieldRva {

    val stub = BaseWinMdStub(objectMapper, navigator, index)

    override fun getStub(): WinMdStub {
        return stub
    }

    override fun getToken(): UInt {
        return stub.getToken(CLRMetadataType.FIELD_RVA)
    }

    override fun getOffset(): UInt {
        return stub.getObjectTableOffset(CLRMetadataType.FIELD_RVA, 0).toUInt()
    }

    override fun copy(rowNum: Int): StubFieldRvaImpl {
        return StubFieldRvaImpl::class.constructors.first().call(stub.getObjectMapper(), stub.getNavigator(), rowNum)
    }

    override fun getField(): com.github.danielchemko.winmdj.core.mdspec.Field? {
        return stub.lookupConcreteReferent(
            CLRMetadataType.FIELD_RVA,
            1,
            com.github.danielchemko.winmdj.core.mdspec.Field::class
        )
    }

    override fun getFieldOffset(): kotlin.UInt {
        return stub.lookupTableValue(CLRMetadataType.FIELD_RVA, 0, kotlin.UInt::class)!!
    }
}